### ISSUE TITLE
Installation instructions should make clearer where c3 should be added

### ISSUE THREAD

**Issue by arturojain** [ArturRod/dicom-ecg#1]
Based on installation instructions I'm not sure where `"c3": "^0.7.20"` should be added.

**Comment by ArturRod** [comment]
Hi, @arturojain 
Yes, sorry, it's in the main OHIF project in package.json.
Inside package.json in dependencies.

**Comment by arturojain** [comment]
Looking at the latest README, should `yarn add c3@^0.7.20 -W` be used?

**Comment by ArturRod** [comment]
@arturojain 
Yes, you can add it manually in package.json and then do an npm install or install it with yarn, both options are valid. In the end it is an extension for OHIF Viewer, it works in the same way as the OHIF components, everything comes from the OHIF documentation.
