### ISSUE TITLE
Intallation notes

### ISSUE THREAD

**Issue by realvgm** [ArturRod/dicom-ecg#3]
Hello;

This add-on for OHIF seems very interesting. We would like to test your plugin for displaying ECGs. But we are not very clear about the notes to integrate it into OHIF. Can you tell us more about the process?

Thanks.

**Comment by ArturRod** [comment]
Hi @realvgm 
Thanks for your interest, I am preparing an INSTALLATION.MD file explaining the steps to be able to add the extension in OHIF VIEWER.

**Comment by ArturRod** [comment]
https://github.com/ArturRod/dicom-ecg/blob/main/INSTALLATION.md

**Comment by realvgm** [comment]
Hi;

Thanks a lot!!

One thing, if I put "Import OHIFDicomECGExtension from '@ohif/extension-dicom-ecg'" with "I" in capital letter, I get an error. With an "i" in lowercase, it works. Can be??

Thanks

pd: We're from Barcelona.

**Comment by realvgm** [comment]
Hi;

Two more question. In the INSTALLATION.MD, I'm confuse about point 2 and 3.

Point 2, what is the path to find "Add the extension in OHIF-Viewer (platform/package.json) add the extension:"?? On Path <OHIF_base_path>/platform, there is no package.json.

Point 3, what is the path to find "Add c3 dependency in OHIF-Viewer (package.json)"?? Is the package.json located on the base OHIF path (<OHIF_base_path>)??

Thank you a lot!!

**Comment by ArturRod** [comment]
Hi @realvgm 
Point 2 update Installation.md -> route platform/viewer/package.json
Point 3 -> Is the package.json of the project. It is in the main folder of the project.

**Comment by realvgm** [comment]
thanks thanks thanks

**Comment by ArturRod** [comment]
@realvgm
I have requested a pull of the project, you have the branch in case it is easier for you to download and work.
https://github.com/OHIF/Viewers/pull/2854

**Comment by realvgm** [comment]
WoW!! Great news!!

Thanks a lot, all works perfectly now. Your help has been invaluable.
