### ISSUE TITLE
Problems with extension v1.0.6 and OHIF v2 (4.12.51)

### ISSUE THREAD

**Issue by realvgm** [ArturRod/dicom-ecg#7]
Note: for all the screenshots the opening of the same DICOM object has been performed (we attach the DICOM file used in the examples) -> [ecgAnon_fo.zip](https://github.com/ArturRod/dicom-ecg/files/11723174/ecgAnon_fo.zip)

We are experiencing problems with the v1.0.6 version of the extension to view ECGs with OHIF v2 (4.12.51). Specifically, when we view an ECG-type DICOM object, the waveforms are not shown (although the demographics are).
![ohif_ecg_1](https://github.com/ArturRod/dicom-ecg/assets/35485242/aebfe6f6-a74a-4e09-ac1a-60efce805215)

With version v1.0.3 or lower of the extension, the waveform is shown.
![ohif_ecg_2](https://github.com/ArturRod/dicom-ecg/assets/35485242/f438c124-92f9-40bf-996a-64e3d75e8c58)

But, we notice significant differences in the waveforms if we compare them with what is shown by other viewers.
![ohif_ecg_3](https://github.com/ArturRod/dicom-ecg/assets/35485242/d7dc7c51-68b8-4184-8580-536e96505dc7)

We would like to know if you plan to release a v1.0.7 of the OHIF v2 plugin, and if you would kindly review these problems that we discussed.

Thanks.

**Comment by ArturRod** [comment]
Hi @realvgm
With the new version of ECG these problems are solved, it also allows you to see more data from the dcm.
https://github.com/ArturRod/ecg-dicom-web-viewer
It remains to be implemented in ohif, in a short time it will be done.

**Comment by ArturRod** [comment]
Hi @realvgm 
It has already been fixed with the latest versions.
