### ISSUE TITLE
Is there a good source for sample files for testing?

### ISSUE THREAD

**Issue by jensen0914** [ArturRod/dicom-ecg#8]
Just a question, no real issue. I've integrated this extension into my fork of OHIF following the instructions and all seems to be working with a couple of 12-lead DICOM ECG files I've found. Do you have any suggestions for a source of sample files that can test all four of the supported SOP Classes this extension is coded to handle?

Thanks,

Todd Jensen, PhD
Jensen Informatics LLC

**Comment by ArturRod** [comment]
Hi @jensen0914.
Currently I do not have anonymized studies to be able to upload and test, the tests I did are with real studies, if you have an anonymized study willing to share or that I have found on the internet, I can add it to the ecg-dicom-web-viewer and so have one type of each :)
